// *******************************************************************************
// Copyright (c) 2025 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License Version 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// *******************************************************************************

use logos::Logos;
use std::{fmt, ops};

use crate::source::LocalSpan;

#[derive(Clone, Copy, PartialEq, Eq, Logos)]
// 's is the source lifetime used in the code generated by Logos
#[logos(error(&'s str, Lexer::slice))]
#[logos(skip r"[ \t\n\f]+")] // Ignore whitespace between tokens
pub enum Lexeme<'src> {
    #[regex("[a-zA-Z_][a-zA-Z0-9_]*")]
    Word(&'src str),

    #[regex("[0-9]+")]
    Integer(&'src str),

    #[regex("//!.*", inner_doc)]
    InnerDoc(LocalSpan),
    #[regex("///.*", outer_doc)]
    OuterDoc(LocalSpan),

    #[token(",")]
    Comma,
    #[token(";")]
    Semicolon,
    #[token(":")]
    Colon,
    #[token("::")]
    DoubleColon,
    #[token("=")]
    Equals,
    #[token("#")]
    Hash,

    #[token("<")]
    OpenAngle,
    #[token(">")]
    CloseAngle,

    #[token("{")]
    OpenBrace,
    #[token("}")]
    CloseBrace,

    #[token("(")]
    OpenParen,
    #[token(")")]
    CloseParen,

    #[token("[")]
    OpenSquare,
    #[token("]")]
    CloseSquare,

    Invalid(&'src str),
}

fn inner_doc<'src>(lex: &logos::Lexer<'src, Lexeme<'src>>) -> Option<LocalSpan> {
    // Skip the `//!` prefix
    let span = lex.span();
    Some(LocalSpan {
        start: span.start + 3,
        end: span.end,
    })
}

fn outer_doc<'src>(lex: &logos::Lexer<'src, Lexeme<'src>>) -> Option<LocalSpan> {
    // Skip the `///` prefix
    let span = lex.span();
    Some(LocalSpan {
        start: span.start + 3,
        end: span.end,
    })
}

impl fmt::Debug for Lexeme<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Word(s) => f.write_str(s),
            Self::Integer(s) => f.write_str(s),
            Self::InnerDoc(_) => f.write_str("//!"),
            Self::OuterDoc(_) => f.write_str("///"),
            Self::Comma => f.write_str(","),
            Self::Semicolon => f.write_str(";"),
            Self::Colon => f.write_str(":"),
            Self::DoubleColon => f.write_str("::"),
            Self::Equals => f.write_str("="),
            Self::Hash => f.write_str("#"),
            Self::OpenAngle => f.write_str("<"),
            Self::CloseAngle => f.write_str(">"),
            Self::OpenBrace => f.write_str("{"),
            Self::CloseBrace => f.write_str("}"),
            Self::OpenParen => f.write_str("("),
            Self::CloseParen => f.write_str(")"),
            Self::OpenSquare => f.write_str("["),
            Self::CloseSquare => f.write_str("]"),
            Self::Invalid(_) => f.write_str("❌"),
        }
    }
}

pub fn lex<'src>(input: &'src str) -> impl Iterator<Item = (Lexeme<'src>, LocalSpan)> + 'src {
    Lexeme::lexer(input)
        .spanned()
        .map(move |(token_result, span)| {
            let token = token_result.unwrap_or_else(Lexeme::Invalid);
            let span = LocalSpan {
                start: span.start,
                end: span.end,
            };
            (token, span)
        })
}
